# action.yml
name: 'Rust Cargo Deb Package Build (amd64 and aarch64, Ubuntu)'
description: 'Builds a statically linked .deb package, amd64, aarch64 musl, ubuntu'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  cmd1:
    description: 'First build command'
    required: true
    default: 'cargo deb --target=x86_64-unknown-linux-musl'
  cmd2:
    description: 'Second build command'
    required: true
    default: 'cargo deb --target=aarch64-unknown-linux-musl'
runs:
  using: 'docker'
  image: 'docker://payshort/cargo-deb-ubuntu:main' # Need to update to use release docker image
  entrypoint: '/bin/bash'
  args:
    - ${{ inputs.cmd }}