# action.yml
name: 'Rust Cargo Deb Package Build (amd64 and aarch64, Ubuntu)'
description: 'Builds a statically linked .deb package, amd64, aarch64 musl, ubuntu'
branding:
  icon: 'package'
  color: 'orange'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - 'x86_64-unknown-linux-musl'
          - 'aarch64-unknown-linux-musl'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build .deb package
        uses: docker://payshort/cargo-deb-ubuntu:main
        with:
          cmd: 'cargo deb --target=${{ matrix.target }}'